#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
  exec startx -- -config ~/.local/share/xorg/00_xenos_xorg_hardening.conf -keeptty &> ~/.local/share/xorg/Xorg-stdout-stderr.log -nolisten tcp -terminate
fi
